pipeline:
  name: Aurora-Snowflake-Sync-Deploy
  identifier: AuroraSnowflakeSyncDeploy
  projectIdentifier: DefaultProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Infrastructure
        identifier: Deploy_Infrastructure
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: Terraform Apply
                  identifier: Terraform_Apply
                  spec:
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            type: Github
                            spec:
                              gitFetchType: Branch
                              branch: main
                              folderPath: terraform
                              connectorRef: account.Github_Connector
                    provisionerIdentifier: default
                    workspace: aurora-snowflake-sync
